/* MyLoon Box
   Reads manifest.json generated by GitHub Actions and renders an
   installable list. No framework, no build step, no runtime dependency.

   All plugin fields are inserted with textContent, never as HTML, so a
   hostile manifest cannot inject markup into the page. */

const MANIFEST_URL = new URL("manifest.json", document.baseURI).href;
const RAW_BASE = "https://raw.githubusercontent.com/OliviaR13/MyLoon/main/";

const ALL = "全部";

const state = { plugins: [], category: ALL, query: "" };

const els = {
  results: document.getElementById("results"),
  count: document.getElementById("countText"),
  updated: document.getElementById("updatedText"),
  filters: document.getElementById("filters"),
  search: document.getElementById("searchInput"),
  refresh: document.getElementById("refreshBtn"),
  rowTpl: document.getElementById("rowTpl"),
  toast: document.getElementById("toast"),
};

/* ---------- helpers ---------- */

function isSafeIcon(value) {
  if (!value) return false;
  try {
    const url = new URL(value, document.baseURI);
    return url.protocol === "https:" || url.protocol === "http:";
  } catch {
    return false;
  }
}

function pluginDownloadURL(plugin) {
  return RAW_BASE + String(plugin.file || "").replace(/^\/+/, "");
}

let toastTimer = 0;
function toast(message) {
  els.toast.textContent = message;
  els.toast.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => els.toast.classList.remove("show"), 2200);
}

/* ---------- normalize ---------- */

function normalize(raw) {
  return {
    id: String(raw.id || raw.file || Math.random()),
    name: String(raw.name || raw.file || "未命名插件"),
    file: String(raw.file || ""),
    version: raw.version ? String(raw.version) : "",
    author: String(raw.author || "MyLoon"),
    category: String(raw.category || "其他"),
    icon: String(raw.icon || ""),
    description: String(raw.description || ""),
  };
}

function matches(plugin) {
  if (state.category !== ALL && plugin.category !== state.category) return false;
  const q = state.query.trim().toLowerCase();
  if (!q) return true;
  return [plugin.name, plugin.description, plugin.author, plugin.category]
    .join(" ")
    .toLowerCase()
    .includes(q);
}

/* ---------- rendering ---------- */

function buildRow(plugin) {
  const row = els.rowTpl.content.firstElementChild.cloneNode(true);
  row.dataset.id = plugin.id;

  const icon = row.querySelector(".plugin-icon");
  if (isSafeIcon(plugin.icon)) {
    icon.src = plugin.icon;
  } else {
    icon.remove();
  }

  row.querySelector(".plugin-name").textContent = plugin.name;
  row.querySelector(".chip-version").textContent = plugin.version;
  row.querySelector(".chip-cat").textContent = plugin.category;
  row.querySelector(".plugin-author").textContent = plugin.author;

  const desc = row.querySelector(".plugin-desc");
  desc.textContent = plugin.description;
  desc.dataset.clamped = "true";

  const toggle = row.querySelector(".plugin-toggle");
  const toggleLabel = toggle.querySelector(".toggle-label");
  toggle.addEventListener("click", () => {
    const open = toggle.getAttribute("aria-expanded") === "true";
    toggle.setAttribute("aria-expanded", String(!open));
    desc.dataset.clamped = String(open);
    toggleLabel.textContent = open ? "展开全文" : "收起";
  });

  row.querySelector(".plugin-install").addEventListener("click", () => {
    window.location.href =
      "loon://install?url=" + encodeURIComponent(pluginDownloadURL(plugin));
    toast("已尝试调用 Loon 安装 " + plugin.name);
  });

  return row;
}

function fitToggles() {
  requestAnimationFrame(() => {
    els.results.querySelectorAll(".plugin").forEach((row) => {
      const desc = row.querySelector(".plugin-desc");
      const toggle = row.querySelector(".plugin-toggle");
      if (!desc || !toggle) return;
      toggle.hidden = desc.scrollHeight <= desc.clientHeight + 2;
    });
  });
}

function buildNotice(variant, heading, body, actionLabel, onAction) {
  const wrap = document.createElement("div");
  wrap.className = "notice notice-" + variant;

  const alertIcon = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  alertIcon.setAttribute("class", "ico");
  alertIcon.setAttribute("aria-hidden", "true");
  const use = document.createElementNS("http://www.w3.org/2000/svg", "use");
  use.setAttribute("href", variant === "alert" ? "#i-alert" : "#i-search");
  alertIcon.append(use);

  const inner = document.createElement("div");
  const h = document.createElement("h2");
  h.textContent = heading;
  const p = document.createElement("p");
  p.textContent = body;
  inner.append(h, p);

  if (actionLabel) {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "btn";
    btn.textContent = actionLabel;
    btn.addEventListener("click", onAction);
    inner.append(btn);
  }

  wrap.append(alertIcon, inner);
  return wrap;
}

function renderSkeleton() {
  const frag = document.createDocumentFragment();
  for (let i = 0; i < 4; i += 1) {
    const sk = document.createElement("div");
    sk.className = "sk";
    sk.innerHTML =
      '<div class="sk-box sk-icon"></div>' +
      '<div class="sk-lines">' +
      '<div class="sk-box sk-line sk-w-40"></div>' +
      '<div class="sk-box sk-line sk-w-90"></div>' +
      '<div class="sk-box sk-line sk-w-70"></div>' +
      "</div>" +
      '<div class="sk-box sk-btn"></div>';
    frag.append(sk);
  }
  els.results.replaceChildren(frag);
}

function render() {
  const visible = state.plugins.filter(matches);

  els.count.textContent = visible.length
    ? `${visible.length} / ${state.plugins.length} 个插件`
    : `共 ${state.plugins.length} 个插件`;

  const frag = document.createDocumentFragment();

  if (!visible.length) {
    frag.append(
      buildNotice(
        "empty",
        state.plugins.length ? "没有匹配的插件" : "清单里还没有插件",
        state.plugins.length
          ? "换个关键词，或者把分类切回全部再看看。"
          : "manifest.json 里没有返回任何插件条目。",
        "清除筛选",
        resetFilters
      )
    );
  } else {
    visible.forEach((plugin) => frag.append(buildRow(plugin)));
  }

  els.results.replaceChildren(frag);
  fitToggles();
}

/* ---------- filters ---------- */

function renderFilters() {
  const categories = [ALL, ...new Set(state.plugins.map((p) => p.category))];
  const frag = document.createDocumentFragment();

  categories.forEach((category) => {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "chip-filter";
    btn.textContent = category;
    btn.setAttribute("aria-pressed", String(state.category === category));
    btn.addEventListener("click", () => {
      state.category = category;
      renderFilters();
      render();
    });
    frag.append(btn);
  });

  els.filters.replaceChildren(frag);
}

function resetFilters() {
  state.category = ALL;
  state.query = "";
  els.search.value = "";
  renderFilters();
  render();
  els.search.focus();
}

/* ---------- data ---------- */

async function loadManifest(announce = false) {
  els.results.setAttribute("aria-busy", "true");
  els.refresh.disabled = true;
  renderSkeleton();
  els.count.textContent = "正在加载清单";
  els.updated.textContent = "";

  try {
    const response = await fetch(`${MANIFEST_URL}?t=${Date.now()}`, { cache: "no-store" });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);

    const data = await response.json();
    state.plugins = (data.plugins || []).map(normalize);
    state.category = ALL;

    renderFilters();
    render();

    if (data.generatedAt) {
      els.updated.textContent =
        "清单更新于 " +
        new Intl.DateTimeFormat("zh-CN", {
          year: "numeric",
          month: "2-digit",
          day: "2-digit",
        }).format(new Date(data.generatedAt));
    }

    if (announce) toast("清单已刷新");
  } catch (error) {
    console.error(error);
    els.count.textContent = "清单加载失败";
    els.updated.textContent = "";
    els.results.replaceChildren(
      buildNotice(
        "alert",
        "暂时拿不到插件清单",
        "可能是网络问题，或者 manifest.json 还没生成。可以重试，也可以直接去 GitHub 仓库的 plugin 目录手动取 raw 链接。",
        "重试",
        () => loadManifest(true)
      )
    );
  } finally {
    els.refresh.disabled = false;
    els.results.setAttribute("aria-busy", "false");
  }
}

/* ---------- wiring ---------- */

let searchTimer = 0;
els.search.addEventListener("input", (event) => {
  const value = event.target.value;
  clearTimeout(searchTimer);
  searchTimer = setTimeout(() => {
    state.query = value;
    render();
  }, 120);
});

els.search.addEventListener("keydown", (event) => {
  if (event.key === "Escape" && event.target.value) {
    event.target.value = "";
    state.query = "";
    render();
  }
});

els.refresh.addEventListener("click", () => loadManifest(true));

document.addEventListener("keydown", (event) => {
  if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
    event.preventDefault();
    els.search.focus();
    els.search.select();
  }
});

const kbd = document.getElementById("kbdHint");
if (kbd && /Mac|iPhone|iPad|iPod/.test(navigator.platform || navigator.userAgent)) {
  kbd.textContent = "⌘ K";
}

loadManifest();
